adding comments functionality to each article selected
jm-w-a/fe-nc-news pull request #4
Opened 2023-07-18 14:23 UTC by jm-w-a

Adding comments functionality to each article selected

2023-07-18 14:29 UTC, popatre requested changes
- Good to see the axios requests extracted into their own folder - nice and reusable
- Lovely stuff creating a separate component for the comments; stops the components getting too big and bloated
- Good that we've got the comments for the correct article showing 👍
- Excellent work displaying the comments

- [ ] We need some loading feedback for a better UX - let the user know that something is happening/comments are being requested
- [ ] Would be good for the articles which have no comments to get a little messages saying so e.g. 'No comments to show - why not be the first to add one?'

2023-07-18 14:29 UTC, popatre commented on src/components/Comments.jsx
> +  }, [article_id]);
Think this would work without the article_id as a dependency.

2023-07-18 14:29 UTC, popatre commented on src/components/Comments.jsx
> +                  <br />
might be nicer to use css to get the gap you need - but upto you

2023-07-19 10:26 UTC, robert112233 approved these changes
Well done for implementing Jonathan's feedback, good to merge!

2023-07-20 07:56 UTC, merged